=== jlambert68/FenixSubCustodyTestInstructionAdmin/TestInstructionsAndTesInstructionContainersAndAllowedUsers/TestInstructions/TestInstruction_VerifyMQTypeMT_VerifyContentTypeMT5xx/version_1_0/VerifyMQTypeMT_VerifyContentTypeMT5xx.json-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Verify that a message of type MT5xx was received, version 1.0",
  "type": "object",
  "properties": {
    "testStepClassName": {
      "type": "string",
      "enum": [
        "VerifyMQTypeMT"
      ]
    },
    "testStepActionMethod": {
      "type": "string",
      "enum": [
        "VerifyContentTypeMT5xx_v1_0"
      ]
    },
    "testDataParameterType": {
      "type": "string",
      "enum": [
        "FixedValue"
      ]
    },
    "expectedToBePassed": {
      "type": "boolean",
      "enum": [
        true,
        false
      ]
    },
    "methodParameters": {
      "type": "object",
      "$ref": "#/definitions/MethodParameters"
    }
  },
  "required": [
    "testStepClassName",
    "testStepActionMethod",
    "testDataParameterType",
    "expectedToBePassed",
    "methodParameters"
  ],
  "additionalProperties": false,
  "definitions": {
    "MethodParameters": {
      "type": "object",
      "properties": {
        "MethodParametersJsonAsString": {
          "type": "string"
        }
      },
      "required": [
        "MethodParametersJsonAsString"
      ],
      "additionalProperties": false
    }
  }
}

=== jlambert68/FenixSubCustodyTestInstructionAdmin/TestInstructionsAndTesInstructionContainersAndAllowedUsers/TestInstructions/TestInstruction_VerifyMQTypeMT_VerifyContentTypeMT5xx/version_1_0/VerifyMQTypeMT_VerifyContentTypeMT5xx-example.json
{
  "testStepClassName": "VerifyMQTypeMT",
  "testStepActionMethod": "VerifyContentTypeMT5xx_v1_0",
  "testDataParameterType": "FixedValue",
  "methodParameters": {
    "MethodParametersJsonAsString": "{\"TestStepActionMethod\": \"VerifyContentTypeMT5xx_v1_0\",  \"TestInstructionVersion\": \"v1.0\",  \"ExpectedToBePassed\": \"true\",  \"TestCaseExecutionUuid\": \"a0161997-4323-45a8-93fa-8ff7d64d1b7a\",  \"TestInstructionExecutionUuid\": \"ae344db4-2d34-474e-bd91-1b24ac408b75\",  \"TestInstructionExecutionVersion\": \"1\",  \"TimeoutTimeInSeconds\": \"600\",  \"RelatedReference_5xx_20CRELA\": \"323840-3389\",  \"MessageType_5xx\": \"MT540\"}"
  },
  "expectedToBePassed": true
}
