=== jlambert68/FenixSubCustodyTestInstructionAdmin/TestInstructionsAndTesInstructionContainersAndAllowedUsers/TestInstructions/TestInstruction_FenixGeneral_SendTemplateToThisDomain/version_1_0/FenixGeneral_SendTemplateToThisDomain.json-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "FenixGeneral_SendTemplateToThisDomain Request, version 1.0",
  "type": "object",
  "properties": {
    "testCaseExecutionId": {
      "type": "string"
    },
    "testStepClassName": {
      "type": "string",
      "enum": [
        "FenixGeneral"
      ]
    },
    "testStepActionMethod": {
      "type": "string",
      "enum": [
        "SendTemplateToThisDomain_v1_0"
      ]
    },
    "testDataParameterType": {
      "type": "string",
      "enum": [
        "FixedValue"
      ]
    },
    "expectedToBePassed": {
      "type": "boolean",
      "enum": [
        true,
        false
      ]
    },
    "methodParameters": {
      "type": "object",
      "$ref": "#/definitions/MethodParameters"
    }
  },
  "required": [
    "testCaseExecutionId",
    "testStepClassName",
    "testStepActionMethod",
    "testDataParameterType",
    "expectedToBePassed",
    "methodParameters"
  ],
  "additionalProperties": false,
  "definitions": {
    "MethodParameters": {
      "type": "object",
      "properties": {
        "MethodParametersJsonAsString": {
          "type": "string"
        }
      },
      "required": [
        "MethodParametersJsonAsString"
      ],
      "additionalProperties": false
    }
  }
}

=== jlambert68/FenixSubCustodyTestInstructionAdmin/TestInstructionsAndTesInstructionContainersAndAllowedUsers/TestInstructions/TestInstruction_FenixGeneral_SendTemplateToThisDomain/version_1_0/FenixGeneral_SendTemplateToThisDomain-example.json
{
  "testCaseExecutionId": "a0161997-4323-45a8-93fa-8ff7d64d1b7a",
  "testStepClassName": "FenixGeneral",
  "testStepActionMethod": "SendTemplateToThisDomain_v1_0",
  "testDataParameterType": "FixedValue",
  "methodParameters": {
    "MethodParametersJsonAsString": "{\"TestInstructionVersion\": \"v1.0\", \"ExpectedToBePassed\": \"true\", \"TestCaseExecutionUuid\": \"a0161997-4323-45a8-93fa-8ff7d64d1b7a\", \"TestInstructionExecutionUuid\": \"ae344db4-2d34-474e-bd91-1b24ac408b75\", \"TestInstructionExecutionVersion\": \"1\", \"TestInstructionVersion\": \"v1.0\", \"TimeoutTimeInSeconds\": \"30\"}"
  },
  "expectedToBePassed": true
}
